### PR TITLE
Add worker template, restructure docker setup

### PR DESCRIPTION
**Pull request by weskamm**
This introduces a worker template which can be used for easier setup of a worker.
Both existing workers have been adjusted to make use of the template.

Besides, docker setup has been modified to include the template and to reduce file copying.

@mholthausen please review

### CODE REVIEW

**Review by mholthausen — COMMENTED** [review]
Neat, looks good to me overall. But I think for the extract job the file path isn't processed correctly yet: 
```
Error caught: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
```

**Comment by weskamm** [comment]
This is intended, as the job specification currently has to look like this:

```
  "job": [
        {
            "type": "download",
            "datasetURI": "https://github.com/terrestris/fossgis2021/raw/main/talks/shogun.pdf"
        },
        {
            "type": "extract",
            "fileURI": "/home/data/test.gz"
        }
    ],
    "emailAddress": "peter@tosh.com"
}
```

**Review by mholthausen — APPROVED** [review]
Works with corresponding parameters (e.g. `fileURI` in `/home/data/[…]` for `extract`)
Can be merged now 👍🏻

**Comment by weskamm** [comment]
Thanks for review!

**Pull request merged**
