### PR TITLE
Prepare jest

### PR DESCRIPTION
**Pull request by hwbllmnn**
Unit tests can now be added and run via jest.

### CODE REVIEW

**Comment by JakobMiksch** [comment]
@hwbllmnn why do we need the ts-config file?

**Review by JakobMiksch — COMMENTED** [review]
Looks cool so far. Some notes in the README would be great.

**Comment by hwbllmnn** [comment]
> @hwbllmnn why do we need the ts-config file?

It makes jest go into transpiling mode, I had problems with modules like `ol` or `node-fetch` not being transpiled.

**Comment by hwbllmnn** [comment]
Ok, I've added some more tests and added a few words to the README.

**Review by JakobMiksch — APPROVED** [review]
I tested it and it works fine. Great work. I am looking forward writing more tests.
one minor comment:
could you add a note in the readme what the docker-compse.yml is about?

**Pull request merged**
